const _e = [
	{
		user: "U0927N91N0K",
		type: "message",
		ts: "1769798652.718629",
		edited: {
			user: "B0927N91F3M",
			ts: "1769800238.000000",
		},
		bot_id: "B0927N91F3M",
		app_id: "A092ENE1EG4",
		text: "updated by the bot",
		team: "T048EJ33W",
		bot_profile: {
			id: "B0927N91F3M",
			deleted: false,
			name: "1on1-order-generator",
			updated: 1750457044,
			app_id: "A092ENE1EG4",
			user_id: "U0927N91N0K",
			icons: {
				image_36: "https://a.slack-edge.com/80588/img/plugins/app/bot_36.png",
				image_48: "https://a.slack-edge.com/80588/img/plugins/app/bot_48.png",
				image_72:
					"https://a.slack-edge.com/80588/img/plugins/app/service_72.png",
			},
			team_id: "T048EJ33W",
		},
		thread_ts: "1769798652.718629",
		reply_count: 3,
		reply_users_count: 2,
		latest_reply: "1769800231.663219",
		reply_users: ["U0927N91N0K", "U05083TTS74"],
		is_locked: false,
		subscribed: false,
		attachments: [
			{
				from_url: "https://slack-cronjob.vercel.app/",
				id: 1,
				original_url: "https://slack-cronjob.vercel.app/",
				fallback: "Create Next App",
				text: "Generated by create next app",
				title: "Create Next App",
				title_link: "https://slack-cronjob.vercel.app/",
				service_name: "slack-cronjob.vercel.app",
			},
		],
		blocks: [
			{
				type: "section",
				block_id: "qFtaI",
				fields: [
					{
						type: "mrkdwn",
						text: "*:mega: 1on1 order* \n This order is for the meeting on Saturday, January 31, 2026.",
						verbatim: false,
					},
					{
						type: "mrkdwn",
						text: "*:alarm_clock: Updated at(UTC+9):*\n 04:10 Saturday, January 31, 2026",
						verbatim: false,
					},
				],
			},
			{
				type: "section",
				block_id: "dHIXP",
				text: {
					type: "mrkdwn",
					text: "You can toggle your progress display",
					verbatim: false,
				},
				accessory: {
					type: "button",
					action_id: "toggle_1on1_progress",
					style: "primary",
					text: {
						type: "plain_text",
						text: "Finished/Not Yet",
						emoji: true,
					},
					value: "click_me_123",
				},
			},
			{
				type: "header",
				block_id: "4Y1IS",
				text: {
					type: "plain_text",
					text: ":chair:Offline Orders",
					emoji: true,
				},
			},
			{
				type: "section",
				block_id: "KRZ7U",
				text: {
					type: "mrkdwn",
					text: ":white_check_mark: <@U05083TTS74>",
					verbatim: false,
				},
				accessory: {
					type: "button",
					action_id: "button-action",
					text: {
						type: "plain_text",
						text: "Join Huddle",
						emoji: true,
					},
					value: "click_me_123",
					url: "https://app.slack.com/huddle/T048EJ33W/C09R2EFQSLE",
				},
			},
			{
				type: "divider",
				block_id: "+o3v3",
			},
			{
				type: "section",
				block_id: "7Py+3",
				text: {
					type: "mrkdwn",
					text: "Want to edit the upcoming slot? \n Visit <https://slack-cronjob.vercel.app/>",
					verbatim: false,
				},
			},
		],
	},
];
