type Channel {
  channelId: ID!
  channelName: String!
  userIds: [ID!]!
  day: Day!
}

enum Day {
  MONDAY
  TUESDAY
  WEDNESDAY
  THURSDAY
  FRIDAY
  SATURDAY
  SUNDAY
}

extend type Query {
  channels: [Channel!]!
}

extend type Mutation {
  addChannel(
    channelId: ID!
    channelName: String!
    userIds: [ID!]!
    day: Day!
  ): AddChannelResponse!
  registerUsers(channelId: ID!, userIds: [ID!]!): RegisterUserResponse!
}

type AddChannelResponse {
  success: Boolean!
  error: String
}

type RegisterUserResponse {
  success: Boolean!
  error: String
}
