type User {
  id: ID!
  name: String!
}

extend type Query {
  users: [User!]!
}

extend type Mutation {
  addUser(id: ID!, name: String!): AddUserResponse!
}

type AddUserResponse {
  success: Boolean!
}
