query GetChannels {
  channels {
    channelId
    channelName
    userIds
    day
  }
}

mutation AddChannel(
  $channelId: ID!
  $channelName: String!
  $userIds: [ID!]!
  $day: Day!
) {
  addChannel(
    channelId: $channelId
    channelName: $channelName
    userIds: $userIds
    day: $day
  ) {
    success
    error
  }
}

mutation RegisterUsers($channelId: ID!, $userIds: [ID!]!) {
  registerUsers(channelId: $channelId, userIds: $userIds) {
    success
    error
  }
}
